[simulation]
run_mechanical_interactions = false
# bound_space = true
max_displacement = 3.0
leaking_edges = true
calculate_gradients = true

[visualization]
export = false
live = false
export_interval = 1

    [[visualize_sim_object]]
    name = "MyCell"
    additional_data_members = [ "cell_type_" ]

    [[visualize_sim_object]]
    name = "MyNeurite"
    additional_data_members = [ "actual_length_" ]

    # [[visualize_diffusion]]
    # name = "on_diffusion"

    # [[visualize_diffusion]]
    # name = "off_diffusion"

    # [[visualize_diffusion]]
    # name = "off_substance_RGC_guide"
