[simulation]
run_mechanical_interactions = true
bound_space = true
min_bound = 0
max_bound = 150
max_displacement = 3.0

[visualization]
export = true
live = false
export_interval = 1

    [[visualize_sim_object]]
    name = "NeuronSoma"

    [[visualize_sim_object]]
    name = "NeuriteElement"

    # [[visualize_diffusion]]
    # name = "on_diffusion"

    # [[visualize_diffusion]]
    # name = "off_diffusion"
